version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins_network

  python:
    image: python:3.11-slim
    container_name: python
    volumes:
      - .:/workspace
    networks:
      - jenkins_network
    working_dir: /workspace

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
